<?php

/**
 * BaseComentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $autor
 * @property string $email
 * @property string $texto
 * 
 * @method string     getAutor() Returns the current record's "autor" value
 * @method string     getEmail() Returns the current record's "email" value
 * @method string     getTexto() Returns the current record's "texto" value
 * @method Comentario setAutor() Sets the current record's "autor" value
 * @method Comentario setEmail() Sets the current record's "email" value
 * @method Comentario setTexto() Sets the current record's "texto" value
 * 
 * @package    blog
 * @subpackage model
 * @author     pavel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario');
        $this->hasColumn('autor', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('texto', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}