<?php

/**
 * BaseComentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property integer $id
 * @property string $autor
 * @property string $email
 * @property string $texto
 * 
 * @method integer    getPostId()  Returns the current record's "post_id" value
 * @method integer    getId()      Returns the current record's "id" value
 * @method string     getAutor()   Returns the current record's "autor" value
 * @method string     getEmail()   Returns the current record's "email" value
 * @method string     getTexto()   Returns the current record's "texto" value
 * @method Comentario setPostId()  Sets the current record's "post_id" value
 * @method Comentario setId()      Sets the current record's "id" value
 * @method Comentario setAutor()   Sets the current record's "autor" value
 * @method Comentario setEmail()   Sets the current record's "email" value
 * @method Comentario setTexto()   Sets the current record's "texto" value
 * 
 * @package    blog
 * @subpackage model
 * @author     pavel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario');
        $this->hasColumn('post_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('autor', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('texto', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}