<?php

/**
 * BaseComentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pk_post
 * @property integer $id_comentario
 * @property string $autor
 * @property string $email
 * 
 * @method integer    getPkPost()        Returns the current record's "pk_post" value
 * @method integer    getIdComentario()  Returns the current record's "id_comentario" value
 * @method string     getAutor()         Returns the current record's "autor" value
 * @method string     getEmail()         Returns the current record's "email" value
 * @method Comentario setPkPost()        Sets the current record's "pk_post" value
 * @method Comentario setIdComentario()  Sets the current record's "id_comentario" value
 * @method Comentario setAutor()         Sets the current record's "autor" value
 * @method Comentario setEmail()         Sets the current record's "email" value
 * 
 * @package    blog
 * @subpackage model
 * @author     pavel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario');
        $this->hasColumn('pk_post', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_comentario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('autor', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}