<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/03/25 15:01:27
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfformfilterdoctrine' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfformdoctrine' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfdoctrinedataloadtask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinebuildschematask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebasetask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinedropdbtask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinedatadumptask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinemigratetask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinebuildformstask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinedqltask' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sftesterdoctrine' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrineexception' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrineconnectionprofiler' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineconnectionlistener' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinepager' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineroute' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfvalidatordoctrineunique' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfdoctrinegenerator' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformgenerator' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'swift_doctrinespool' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinerecord' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfwidgetformdoctrinechoice' => '/home/pavel/desarrollos/php/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseform' => '/home/pavel/desarrollos/php/blog/lib/form/BaseForm.class.php',
  'basecomentarioform' => '/home/pavel/desarrollos/php/blog/lib/form/doctrine/base/BaseComentarioForm.class.php',
  'basepostform' => '/home/pavel/desarrollos/php/blog/lib/form/doctrine/base/BasePostForm.class.php',
  'comentarioform' => '/home/pavel/desarrollos/php/blog/lib/form/doctrine/ComentarioForm.class.php',
  'postform' => '/home/pavel/desarrollos/php/blog/lib/form/doctrine/PostForm.class.php',
  'baseformdoctrine' => '/home/pavel/desarrollos/php/blog/lib/form/doctrine/BaseFormDoctrine.class.php',
  'basepostformfilter' => '/home/pavel/desarrollos/php/blog/lib/filter/doctrine/base/BasePostFormFilter.class.php',
  'basecomentarioformfilter' => '/home/pavel/desarrollos/php/blog/lib/filter/doctrine/base/BaseComentarioFormFilter.class.php',
  'postformfilter' => '/home/pavel/desarrollos/php/blog/lib/filter/doctrine/PostFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/pavel/desarrollos/php/blog/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'comentarioformfilter' => '/home/pavel/desarrollos/php/blog/lib/filter/doctrine/ComentarioFormFilter.class.php',

  // project_model
  'basecomentario' => '/home/pavel/desarrollos/php/blog/lib/model/doctrine/base/BaseComentario.class.php',
  'basepost' => '/home/pavel/desarrollos/php/blog/lib/model/doctrine/base/BasePost.class.php',
  'comentariotable' => '/home/pavel/desarrollos/php/blog/lib/model/doctrine/ComentarioTable.class.php',
  'post' => '/home/pavel/desarrollos/php/blog/lib/model/doctrine/Post.class.php',
  'posttable' => '/home/pavel/desarrollos/php/blog/lib/model/doctrine/PostTable.class.php',
  'comentario' => '/home/pavel/desarrollos/php/blog/lib/model/doctrine/Comentario.class.php',

  // application
  'myuser' => '/home/pavel/desarrollos/php/blog/apps/backend/lib/myUser.class.php',

  // modules
);
