<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/25 15:02:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=blog',
  'username' => 'postgres',
  'password' => 'postgres',
  'name' => 'doctrine',
)),);
