Post:
  tableName: post
  columns:
    id_post:       { type: integer(4), primary: true, notnull: true }
    titulo:        { type: string(255), notnull: true }
    resumen:	   { type: string(4000) }
    texto:	   { type: string(4000), notnull: true }

    
Comentario:
  tableName: comentario
  columns:
    pk_post:
      type: integer(4)
    id_comentario: { type: integer, primary: true, notnull: true }
    autor:	   { type: string(255) }
    email:	   { type: string(255), notnull: true }
#    texto:	   { type: string(4000), notnull: true }


