Post:
  tableName: post
  columns:
    titulo:        { type: string(255), notnull: true }
    resumen:	   { type: string(400) }
    texto:	   { type: string(4000), notnull: true }

    
Comentario:
  tableName: comentario
  columns:
    autor:	   { type: string(255) }
    email:	   { type: string(255), notnull: true }
    texto:	   { type: string(4000), notnull: true }


